{% raw %}---
# roles/common/defaults/main.yml
common_timezone: {% endraw %}{{ cookiecutter.timezone }}{% raw %}

lc_lang: "en_US.UTF-8"
lc_all: "en_US.utf8"
lc_ctype: "en_US.utf8"
lc_collate: "en_US.utf8"

python_version: 3.7

base_ubuntu:
  common:
    apt_packages:
      - build-essential
      - git
      - htop
      - curl
      - python-dev
      - python-setuptools
      - python3-virtualenv
      - python3-pip
      - "python{{ python_version }}-dev"
      - "python{{ python_version }}-venv"
      - sysstat
      - vim
      - fail2ban
      - libjpeg-dev
      - libtiff5-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - "postgresql-client-{{ postgresql_version }}"
      - libpq-dev
      - ca-certificates
{% endraw %}
